version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - /home/imo046/mariadb:/var/lib/mysql

volumes:
  mariadb_data:
